# Changes here will be overwritten by Copier
_commit: 2.1.4
_src_path: gh:djangoflow/copier-flutter-project
app_description: Odoo timesheets flutter application
app_label: Odoo Timesheets
app_name: timesheets
apple_itc_team_id: null
apple_team_id: null
deep_link_host_prod: null
deep_link_host_sandbox: null
enable_apple_sign_in: false
enable_facebook_sign_in: false
enable_google_sign_in: false
facebook_app_id: null
facebook_client_token: null
firebase_project_id: null
openapi_prod_base_url: null
openapi_sandbox_base_url: null
organization: com.djangoflow.odoo
package_name: com.djangoflow.odoo.timesheets
project_description: Odoo timesheets Flutter project
project_name: flutter-odoo-timesheets
