name: timesheets
description: Odoo timesheets flutter application

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+10

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  auto_route: ^9.2.0
  bloc: ^8.1.2

  djangoflow_app: ^5.0.2
  djangoflow_app_links: ^3.0.0
  drift: ^2.20.2
  flutter_bloc: ^8.1.3
  flutter_screenutil: ^5.8.4
  flex_color_scheme: ^7.1.2
  freezed_annotation: ^2.2.0
  hydrated_bloc: ^9.1.1
  json_annotation: ^4.8.1
  package_info_plus: ^8.0.2
  path: ^1.8.3
  path_provider: ^2.0.15
  progress_builder: ^1.1.3
  scaffold_gradient_background: ^1.0.3+1
  skeletonizer: ^1.4.2
  sqlite3_flutter_libs: ^0.5.15
  drift_db_viewer: ^2.1.0
  djangoflow_sync_drift_odoo: ^0.0.2+1
  djangoflow_odoo_auth: ^0.0.2+1
  djangoflow_sync_foundation: ^0.0.2+1
  provider: ^6.1.2
  flutter_svg: ^2.0.10+1
  vector_graphics: ^1.1.11+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.12
  drift_dev: ^2.20.3
  flutter_lints: ^4.0.0
  flutter_gen_runner: ^5.7.0
  freezed: ^2.5.7
  icons_launcher: ^3.0.0
  json_serializable: ^6.7.0

# Uncomment to override djangoflow_openapi from generated local lib
dependency_overrides:
  lints: ^4.0.0

flutter_gen:
  output: lib/utils/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)
  integrations:
    flutter_svg: true
  # Optional
  assets:
    enabled: true
    outputs:
      style: camel-case

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/app_logo/
    - assets/
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/inter/Inter-Thin.ttf
          weight: 100
        - asset: fonts/inter/Inter-ExtraLight.ttf
          weight: 200
        - asset: fonts/inter/Inter-Light.ttf
          weight: 300
        - asset: fonts/inter/Inter-Regular.ttf
          weight: 400
        - asset: fonts/inter/Inter-Medium.ttf
          weight: 500
        - asset: fonts/inter/Inter-SemiBold.ttf
          weight: 600
        - asset: fonts/inter/Inter-Bold.ttf
          weight: 700
        - asset: fonts/inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: fonts/inter/Inter-Black.ttf
          weight: 900
