name: timesheets
description: Odoo timesheets flutter application

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_route: ^5.0.4
  bloc: ^8.1.0
  countdown_widget: ^2.0.2
  dio: 4.0.4
  djangoflow_app: ^3.0.0
  djangoflow_app_links: ^1.1.3
  flutter_bloc: ^8.1.1
  firebase_core: ^2.4.1
  flex_color_scheme: ^6.1.2
  
  flutter_list_bloc: ^4.0.1
  freezed_annotation: ^2.2.0

  hydrated_bloc: ^9.0.0
  json_annotation: ^4.7.0
  list_bloc: ^3.1.0
  modal_bottom_sheet: ^3.0.0-pre
  package_info_plus: ^3.0.2
  path_provider: ^2.0.11
  progress_builder: ^1.1.3

  reactive_forms: ^14.2.0
  reactive_dropdown_search: ^0.13.0

  responsive_framework: ^0.2.0

  xml_rpc: ^0.4.0
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  icons_launcher: ^2.0.7
  json_serializable: ^6.5.4

# Tempo: until built_value_generator bug is fixed
dependency_overrides:
  dio: 4.0.4
  # Conflict for icons_launcher and flutter_test
  path: 1.8.2
  # Conflict with flutter_test and test packages
  test_api: 0.4.18
  # Conflict between auto_router and xml_rpc
  xml: ^6.0.1
  # Until null check error fixed pushed https://github.com/Milad-Akarie/auto_route_library/pull/1301
  auto_route:
    git:
      url: "https://github.com/djangoflow/auto_route_library.git"
      ref: master
      path: "auto_route"
  auto_route_generator:
    git:
      url: "https://github.com/djangoflow/auto_route_library.git"
      ref: master
      path: "auto_route_generator"
  # Conflict between flutter_localizations and reactive_forms
  intl: ^0.18.0
flutter:
  uses-material-design: true
  assets:
    - assets/app_logo/