name: timesheets
description: Odoo timesheets flutter application

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.1+20

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_route: ^9.2.2
  bloc: ^8.1.2
  djangoflow_app: ^5.0.3
  djangoflow_app_links: ^3.0.0
  drift: ^2.21.0
  drift_flutter: ^0.2.1
  flutter_bloc: ^8.1.3
  flex_color_scheme: ^7.1.2
  freezed_annotation: ^2.2.0
  hydrated_bloc: ^9.1.1
  json_annotation: ^4.8.1
  package_info_plus: ^8.0.2
  path: ^1.8.3
  path_provider: ^2.0.15
  progress_builder: ^1.1.3
  scaffold_gradient_background: ^1.0.3+1
  skeletonizer: ^1.4.2
  sqlite3_flutter_libs: ^0.5.15
  drift_db_viewer: ^2.1.0
  djangoflow_odoo_auth:
    git:
      url: https://github.com/djangoflow/flutter-djangoflow.git
      path: packages/djangoflow_odoo/authentication/djangoflow_odoo_auth
  djangoflow_odoo_oauth: ^0.1.0
  djangoflow_sync_drift_odoo:
    path: /Users/saifulislam/Development/apexlabs/djangoflow/flutter-djangoflow/packages/djangoflow_odoo/sync/djangoflow_sync_drift_odoo
  djangoflow_sync_foundation:
    path: /Users/saifulislam/Development/apexlabs/djangoflow/flutter-djangoflow/packages/djangoflow_odoo/sync/djangoflow_sync_foundation
  provider: ^6.1.2
  flutter_svg: ^2.0.10+1
  vector_graphics: ^1.1.11+1
  responsive_framework: ^1.5.1
  glassmorphism_ui: ^0.3.0
  reactive_dropdown_search: ^5.0.4
  reactive_flutter_typeahead: ^2.1.1
  visibility_detector: ^0.4.0+2
  list_bloc: ^3.1.3
  flutter_list_bloc: ^4.1.4
  auto_animated: ^3.2.0
  reactive_forms: ^17.0.1
  flutter_widget_from_html: ^0.15.2
  intl: ^0.19.0
  rich_readmore: ^1.1.1
  url_launcher: ^6.3.0
  lottie: ^3.1.2
  odoo_rpc:
    git:
      url: https://github.com/djangoflow/odoo-rpc-dart.git
      ref: master
  djangoflow_scrollable_column: ^0.1.0
  collection: ^1.18.0
  djangoflow_error_reporter: ^0.2.0
  djangoflow_sentry_reporter: ^0.3.0
  loader_overlay: ^4.0.2+1
  animated_text_kit: ^4.2.2
  internet_connection_checker: ^1.0.0+1
  internet_connection_checker_plus: ^2.5.2
  custom_refresh_indicator: ^4.0.1
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.13
  drift_dev: ^2.21.0
  flutter_lints: ^4.0.0
  flutter_gen_runner: ^5.7.0
  freezed: ^2.5.7
  icons_launcher: ^3.0.0
  json_serializable: ^6.7.0

# Uncomment to override djangoflow_openapi from generated local lib
dependency_overrides:
  lints: ^4.0.0
  djangoflow_sync_foundation:
    path: /Users/saifulislam/Development/apexlabs/djangoflow/flutter-djangoflow/packages/djangoflow_odoo/sync/djangoflow_sync_foundation

flutter_gen:
  output: lib/utils/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)
  integrations:
    flutter_svg: true
  # Optional
  assets:
    enabled: true
    outputs:
      style: camel-case

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/app_logo/
    - assets/
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/inter/Inter-Thin.ttf
          weight: 100
        - asset: fonts/inter/Inter-ExtraLight.ttf
          weight: 200
        - asset: fonts/inter/Inter-Light.ttf
          weight: 300
        - asset: fonts/inter/Inter-Regular.ttf
          weight: 400
        - asset: fonts/inter/Inter-Medium.ttf
          weight: 500
        - asset: fonts/inter/Inter-SemiBold.ttf
          weight: 600
        - asset: fonts/inter/Inter-Bold.ttf
          weight: 700
        - asset: fonts/inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: fonts/inter/Inter-Black.ttf
          weight: 900
